### ISSUE TITLE
Android recipientId/keyPair storage and/or reuse

### ISSUE THREAD

**Issue by charlesfranciscodev** [VirgilSecurity/virgil-sdk-java-android#9]
Hello I want to follow up the [post](https://github.com/VirgilSecurity/virgil-sdk-java-android/issues/8) using your Android library.

I want to reuse the same recipientId and keyPair that were created initially
when the Android app restarts, so that I can decrypt the stored encrypted text properly.
How can I store and/or reuse the same encryption parameters?

(The problem is that with the code provided the recipientId/keyPair are generated every time and so when the app runs again they are lost and replaced with invalid values.)

**Comment by andrii-iakovenko** [comment]
Hello,

You can store identity, recipientId and keys at preferences. See this example https://github.com/VirgilSecurity/virgil-sdk-java-android/blob/master/samples/twilio-ipmessaging/client/app/src/main/java/com/twilio/ipmessagingquickstart/LoginActivity.java

Verify stored data on activity create

```
if (prefs.contains(Constants.Prefs.IDENTITY)) {
   // Open main activity if user is already registered
   openChat();
   return;
}
```

Store data at app preferences when Virgil Card saved at Virgil Services

```
SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(getBaseContext());
prefs.edit()
   .putString(Constants.Prefs.IDENTITY, mEmail)
   .putString(Constants.Prefs.CARD_ID, mCardId)
   .putString(Constants.Prefs.PRIVATE_KEY, mKeyPair.getPrivate().getAsString())
   .commit();
```

**Comment by charlesfranciscodev** [comment]
Ok that's a possible solution. I will implement it differently because SharedPrefs are not considered safe. That's because SharedPrefs can be read easily on a rooted phone.
